// Mock data for development and testing
// In production, replace with actual API calls

import type { BlinkData, DashboardData } from './types'

export const MOCK_BLINKS: BlinkData[] = [
  {
    id: "colorize-photo",
    slug: "colorize-photo",
    title: "Colorize Photo",
    description: "Transform black & white photos into full color using AI",
    price_usdc: "0.03",
    icon_url: "/lottie/3D Shape Animation.lottie",
    endpoint_url: "https://api.example.com/colorize",
    method: "POST",
    category: "AI/ML",
    runs: 1247,
    status: "active",
    payment_token: "USDC",
    payment_mode: "charge",
    payout_wallet: "8xG...7Kp",
    creator_id: "00000000-0000-0000-0000-000000000000",
    creator: {
      wallet: "8xG...7Kp",
    },
  },
  {
    id: "sentiment-analysis",
    slug: "sentiment-analysis",
    title: "Sentiment Analysis",
    description: "Analyze text sentiment with advanced NLP",
    price_usdc: "0.01",
    icon_url: "/lottie/Circle.lottie",
    endpoint_url: "https://api.example.com/sentiment",
    method: "POST",
    category: "AI/ML",
    runs: 892,
    status: "active",
    payment_token: "USDC",
    payment_mode: "charge",
    payout_wallet: "8xG...7Kp",
    creator_id: "00000000-0000-0000-0000-000000000000",
    creator: {
      wallet: "8xG...7Kp",
    },
  },
  {
    id: "pdf-converter",
    slug: "pdf-converter",
    title: "PDF to Image",
    description: "Convert PDF pages to high-quality images",
    price_usdc: "0.02",
    icon_url: "/lottie/technology.lottie",
    endpoint_url: "https://api.example.com/pdf-convert",
    method: "POST",
    category: "Utilities",
    runs: 2341,
    status: "active",
    payment_token: "USDC",
    payment_mode: "charge",
    payout_wallet: "8xG...7Kp",
    creator_id: "00000000-0000-0000-0000-000000000000",
    creator: {
      wallet: "8xG...7Kp",
    },
  },
  {
    id: "qr-generator",
    slug: "qr-generator",
    title: "QR Code Generator",
    description: "Create custom QR codes with logo and colors",
    price_usdc: "0.01",
    icon_url: "/lottie/3D Shape Animation.lottie",
    endpoint_url: "https://api.example.com/qr",
    method: "POST",
    category: "Utilities",
    runs: 3456,
    status: "active",
    payment_token: "USDC",
    payment_mode: "charge",
    payout_wallet: "8xG...7Kp",
    creator_id: "00000000-0000-0000-0000-000000000000",
    creator: {
      wallet: "8xG...7Kp",
    },
  },
  {
    id: "weather-api",
    slug: "weather-api",
    title: "Weather Data",
    description: "Get current weather for any location worldwide",
    price_usdc: "0.005",
    icon_url: "/lottie/Network connection status.lottie",
    endpoint_url: "https://api.example.com/weather",
    method: "GET",
    category: "Data",
    runs: 5678,
    status: "active",
    payment_token: "USDC",
    payment_mode: "charge",
    payout_wallet: "8xG...7Kp",
    creator_id: "00000000-0000-0000-0000-000000000000",
    creator: {
      wallet: "8xG...7Kp",
    },
  },
  {
    id: "image-optimizer",
    slug: "image-optimizer",
    title: "Image Optimizer",
    description: "Compress and optimize images without quality loss",
    price_usdc: "0.015",
    icon_url: "/lottie/Circle.lottie",
    endpoint_url: "https://api.example.com/optimize",
    method: "POST",
    category: "Utilities",
    runs: 1890,
    status: "active",
    payment_token: "USDC",
    payment_mode: "charge",
    payout_wallet: "8xG...7Kp",
    creator_id: "00000000-0000-0000-0000-000000000000",
    creator: {
      wallet: "8xG...7Kp",
    },
  },
]

export const MOCK_DASHBOARD_DATA: DashboardData = {
  wallet: "8xG...7Kp",
  totalEarnings: "127.45",
  totalRuns: 3842,
  activeBlinks: 8,
  avgPrice: "0.033",
  blinks: [
    {
      id: "colorize-photo",
      slug: "colorize-photo",
      title: "Colorize Photo",
      description: "Transform black & white photos into full color",
      price_usdc: "0.03",
      icon_url: "/lottie/3D Shape Animation.lottie",
      endpoint_url: "https://api.example.com/colorize",
      method: "POST",
      status: "active",
      runs: 1247,
      revenue: "37.41",
      successRate: 98.5,
      lastRun: "2 hours ago",
      category: "AI/ML",
      payment_token: "USDC",
      payment_mode: "charge",
      payout_wallet: "8xG...7Kp",
      creator_id: "00000000-0000-0000-0000-000000000000",
      creator: { wallet: "8xG...7Kp" },
    },
    {
      id: "sentiment-analysis",
      slug: "sentiment-analysis",
      title: "Sentiment Analysis",
      description: "Analyze text sentiment with advanced NLP",
      price_usdc: "0.01",
      icon_url: "/lottie/Circle.lottie",
      endpoint_url: "https://api.example.com/sentiment",
      method: "POST",
      status: "active",
      runs: 892,
      revenue: "8.92",
      successRate: 99.2,
      lastRun: "5 hours ago",
      category: "AI/ML",
      payment_token: "USDC",
      payment_mode: "charge",
      payout_wallet: "8xG...7Kp",
      creator_id: "00000000-0000-0000-0000-000000000000",
      creator: { wallet: "8xG...7Kp" },
    },
    {
      id: "pdf-converter",
      slug: "pdf-converter",
      title: "PDF to Image",
      description: "Convert PDF pages to high-quality images",
      price_usdc: "0.02",
      icon_url: "/lottie/technology.lottie",
      endpoint_url: "https://api.example.com/pdf-convert",
      method: "POST",
      status: "active",
      runs: 2341,
      revenue: "46.82",
      successRate: 97.1,
      lastRun: "1 hour ago",
      category: "Utilities",
      payment_token: "USDC",
      payment_mode: "charge",
      payout_wallet: "8xG...7Kp",
      creator_id: "00000000-0000-0000-0000-000000000000",
      creator: { wallet: "8xG...7Kp" },
    },
    {
      id: "weather-api",
      slug: "weather-api",
      title: "Weather Data",
      description: "Get current weather for any location",
      price_usdc: "0.005",
      icon_url: "/lottie/Network connection status.lottie",
      endpoint_url: "https://api.example.com/weather",
      method: "GET",
      status: "paused",
      runs: 5678,
      revenue: "28.39",
      successRate: 99.8,
      lastRun: "3 days ago",
      category: "Data",
      payment_token: "USDC",
      payment_mode: "charge",
      payout_wallet: "8xG...7Kp",
      creator_id: "00000000-0000-0000-0000-000000000000",
      creator: { wallet: "8xG...7Kp" },
    },
    {
      id: "qr-generator",
      slug: "qr-generator",
      title: "QR Code Generator",
      description: "Create custom QR codes",
      price_usdc: "0.01",
      icon_url: "/lottie/3D Shape Animation.lottie",
      endpoint_url: "https://api.example.com/qr",
      method: "POST",
      status: "active",
      runs: 456,
      revenue: "4.56",
      successRate: 100,
      lastRun: "6 hours ago",
      category: "Utilities",
      payment_token: "USDC",
      payment_mode: "charge",
      payout_wallet: "8xG...7Kp",
      creator_id: "00000000-0000-0000-0000-000000000000",
      creator: { wallet: "8xG...7Kp" },
    },
  ],
  recentActivity: [
    { id: 1, blink: "Colorize Photo", amount: "0.03", time: "2 min ago", status: "success" },
    { id: 2, blink: "PDF to Image", amount: "0.02", time: "5 min ago", status: "success" },
    { id: 3, blink: "Sentiment Analysis", amount: "0.01", time: "12 min ago", status: "success" },
    { id: 4, blink: "Colorize Photo", amount: "0.03", time: "18 min ago", status: "failed" },
    { id: 5, blink: "QR Generator", amount: "0.01", time: "23 min ago", status: "success" },
  ],
}
