import { Keypair } from '@solana/web3.js'

const keypair = Keypair.generate()
const privateKeyArray = Array.from(keypair.secretKey)
const privateKeyBase58 = Buffer.from(keypair.secretKey).toString('base64')
const publicKey = keypair.publicKey.toBase58()

console.log('=== BURNER WALLET GENERATED ===')
console.log('Public Key (Address):', publicKey)
console.log('')
console.log('Private Key (JSON array format):')
console.log(JSON.stringify(privateKeyArray))
console.log('')
console.log('Private Key (Base64):')
console.log(privateKeyBase58)
console.log('')
console.log('⚠️  IMPORTANT: Add this to your .env file:')
console.log(`BURNER_WALLET_PRIVATE_KEY=${privateKeyBase58}`)
console.log(`BURNER_WALLET_PUBLIC_KEY=${publicKey}`)
console.log('')
console.log('Fund this wallet with:')
console.log('- 0.1 SOL (for transaction fees ~20,000 burns)')
console.log('- B402 tokens to burn (e.g., 100,000 B402 = 1000 burns)')
console.log('')
console.log(`View wallet on Solscan: https://solscan.io/account/${publicKey}`)
